### ISSUE TITLE
an endless loop in chapter 3

### ISSUE THREAD

**Issue by sweet-zone** [oreillymedia/data_structures_and_algorithms_using_javascript#9]
we use these code to  traverse the names List in chapter, but, the property 'pos' will alaways less than 'listSize', so there will be a endless loop..

``` javascript
for(names.front(); names.currPos() < names.length(); names.next()) {
print(names. getElement());
}
```

**Comment by karent** [comment]
I've reported this on the title's errata page. You can check it out here: http://www.oreilly.com/catalog/errataunconfirmed.csp?isbn=0636920029557. This should be corrected in the next reprint.
